---
- name: Configure tomcat using child playbooks
  hosts: all
  tasks: 
    - name: Call multiple child playbooks
      include_tasks: "{{item}}"
      with_items: 
        - install_tomcat10.yml
        - copy_tomcat-users.yml
        - change_port.yml
        - restart_tomcat.yml
        - pause.yml
        - check_tomcat_response.yml
...         
