---
- name: fetch the file from server1
  hosts: 172.31.1.23
  tasks: 
    - name: fetch the file
      fetch:
        src: file1
        dest: /tmp
- name: copy file1 to server2
  hosts: 172.31.8.237
  tasks: 
    - name: copy file
      copy:
        src: /tmp/172.31.1.23
        dest: /home/ubuntu





...
