---
- name: Download jenkins.war and change the permission
  hosts: all
  tasks:
    - name: Download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.479.2/jenkins.war
        dest: /tmp
    - name: change permission of the jenkins.war file
      file:
        name: /tmp/jenkins.war
        mode: 760
        owner: ravi
        group: charan




...
