---
- name: Implementing play scope variables
  hosts: all
  vars: 
    - a: tomcat10
    - b: present
    - c: yes
  tasks: 
    - name: Install / uninstall s/w app's
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
