---
- name: Capture os info from all servers
  hosts: all 
  tasks: 
    - name: Capture os name
      debug: 
        var: "{{ansible_distribution}}"
    - name: 
      debug: 
        var: "{{ansible_distribution_version}}"
    - name: 
      debug:
        var: "{{ansible_distribution_major_version}}" 


...
