---
- name: Delete the file if it is empty
  hosts: all
  tasks: 
    - name: Capture file info
      stat: 
        path: /tmp/file100
      register: results
    - name: Display output of the above module
      debug: 
        var: results
    - name: Delete if the file is empty
      file:
        name: /tmp/file100
        state: absent
      when: 
        - results.stat.size == 0

...
